# ref: https://docs.spring.io/spring-cloud-kubernetes/reference/spring-cloud-kubernetes-configserver.html
---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: spring-cloud-kubernetes-configserver
      name: spring-cloud-kubernetes-configserver
      namespace: meetravel-backend
    spec:
      ports:
        - name: http
          port: 8888
          targetPort: 8888
      selector:
        app: spring-cloud-kubernetes-configserver
      type: ClusterIP
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        app: spring-cloud-kubernetes-configserver
      name: spring-cloud-kubernetes-configserver
      namespace: meetravel-backend
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      labels:
        app: spring-cloud-kubernetes-configserver
      name: spring-cloud-kubernetes-configserver:view
      namespace: meetravel-backend
    roleRef:
      kind: ClusterRole
      apiGroup: rbac.authorization.k8s.io
      name: cluster-role
    subjects:
      - kind: ServiceAccount
        name: spring-cloud-kubernetes-configserver
        namespace: meetravel-backend
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: spring-cloud-kubernetes-configserver-deployment
      namespace: meetravel-backend
    spec:
      selector:
        matchLabels:
          app: spring-cloud-kubernetes-configserver
      template:
        metadata:
          labels:
            app: spring-cloud-kubernetes-configserver
        spec:
          serviceAccountName: spring-cloud-kubernetes-configserver
          nodeSelector:
            app: service
          containers:
            - name: spring-cloud-kubernetes-configserver
              image: springcloud/spring-cloud-kubernetes-configserver:3.1.2
              imagePullPolicy: IfNotPresent
              env:
                - name: SPRING_PROFILES_INCLUDE
                  value: "kubernetes"
              readinessProbe:
                httpGet:
                  port: 8888
                  path: /actuator/health/readiness
              livenessProbe:
                httpGet:
                  port: 8888
                  path: /actuator/health/liveness
              ports:
                - containerPort: 8888
