apiVersion: v1
kind: ConfigMap
metadata:
  name: common-configmap
  namespace: meetravel-backend
  labels:
    env: production
    tier: backend
    app: configmap
    name: common-configmap
data:
  TZ: "Asia/Seoul"
